# This file is named service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pizza-pos-service  # The name of your service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/my-pizza-project-123/pizza-repo/pizza-pos:latest  # <-- Update this
          ports:
            - containerPort: 8080  # Your app's port
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db.chxbzrurehvppgqlynfa.supabase.co:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "HootyHoo28!"  # <-- Update this
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"